"""Build the PDF/A-3b preservation envelope (ADR-002).

Input: the rendered PDF pages and the exact validated FHIR IPS bytes.
Output: one PDF/A-3b file that carries
  * the human-readable pages,
  * XMP metadata declaring PDF/A-3 conformance level B,
  * an sRGB output intent,
  * the FHIR IPS JSON as an embedded file, listed in the document-level
    Associated Files (/AF) array with AFRelationship /Source.

Successful generation is NOT evidence of conformance (finding F-010): every
envelope is checked by the pre-flight in ``preflight.py`` and, where
configured, by veraPDF.
"""
from __future__ import annotations

import hashlib
import io
from dataclasses import dataclass
from datetime import datetime

import pikepdf
from pikepdf import Array, Dictionary, Name, String
from PIL import ImageCms

IPS_MIME = "application/fhir+json"


@dataclass(frozen=True)
class Envelope:
    pdf_bytes: bytes
    attachment_name: str
    ips_sha256: str
    pdf_sha256: str


def attachment_name_for(document_id: str) -> str:
    return f"patient-summary-{document_id}.fhir.json"


def envelope_name_for(document_id: str) -> str:
    return f"patient-summary-{document_id}.pdf"


def _pdf_date(dt: datetime) -> str:
    return dt.strftime("D:%Y%m%d%H%M%S+00'00'")


def srgb_icc() -> bytes:
    """sRGB ICC profile generated by LittleCMS (no third-party profile file is redistributed)."""
    return ImageCms.ImageCmsProfile(ImageCms.createProfile("sRGB")).tobytes()


def build_envelope(page_pdf: bytes, ips_json: bytes, *, document_id: str, issued: datetime,
                   title: str, author: str, subject: str) -> Envelope:
    name = attachment_name_for(document_id)
    pdf = pikepdf.open(io.BytesIO(page_pdf))

    # 1. Output intent (sRGB) - required for device-dependent colour in PDF/A.
    icc = pikepdf.Stream(pdf, srgb_icc())
    icc[Name.N] = 3
    pdf.Root[Name.OutputIntents] = Array([Dictionary(
        Type=Name.OutputIntent, S=Name.GTS_PDFA1, OutputConditionIdentifier=String("sRGB IEC61966-2.1"),
        Info=String("sRGB IEC61966-2.1"), DestOutputProfile=icc)])

    # 2. Embedded FHIR IPS as an Associated File (relationship Source).
    mod = _pdf_date(issued)
    ef = pikepdf.Stream(pdf, ips_json)
    ef[Name.Type] = Name.EmbeddedFile
    ef[Name.Subtype] = Name("/" + IPS_MIME)
    ef[Name.Params] = Dictionary(Size=len(ips_json), ModDate=String(mod), CreationDate=String(mod),
                                 CheckSum=String(hashlib.md5(ips_json).digest()))
    filespec = pdf.make_indirect(Dictionary(
        Type=Name.Filespec, F=String(name), UF=String(name),
        Desc=String("HL7 FHIR International Patient Summary (document Bundle) - structured source of this rendition"),
        AFRelationship=Name.Source, EF=Dictionary(F=ef, UF=ef)))
    pdf.Root[Name.AF] = Array([filespec])
    names = pdf.Root.get(Name.Names) or Dictionary()
    names[Name.EmbeddedFiles] = Dictionary(Names=Array([String(name), filespec]))
    pdf.Root[Name.Names] = names
    pdf.Root[Name.PageMode] = Name.UseAttachments     # viewers show the attachment panel

    # 3. Info dictionary and XMP kept consistent; declare PDF/A-3B.
    iso = issued.strftime("%Y-%m-%dT%H:%M:%S+00:00")
    pdf.docinfo[Name.Title] = String(title)
    pdf.docinfo[Name.Author] = String(author)
    pdf.docinfo[Name.Subject] = String(subject)
    pdf.docinfo[Name.CreationDate] = String(mod)
    pdf.docinfo[Name.ModDate] = String(mod)
    with pdf.open_metadata(set_pikepdf_as_editor=False, update_docinfo=False) as meta:
        meta["dc:title"] = title
        meta["dc:creator"] = [author]
        meta["dc:description"] = subject
        meta["dc:format"] = "application/pdf"
        meta["pdf:Producer"] = str(pdf.docinfo.get(Name.Producer, ""))
        meta["xmp:CreatorTool"] = str(pdf.docinfo.get(Name.Creator, ""))
        meta["xmp:CreateDate"] = iso
        meta["xmp:ModifyDate"] = iso
        meta["xmp:MetadataDate"] = iso
        meta["pdfaid:part"] = "3"
        meta["pdfaid:conformance"] = "B"
    # Drop Info entries with no XMP equivalent set above (e.g. ReportLab's empty /Keywords).
    for key in (Name.Trapped, Name.Keywords):
        if key in pdf.docinfo:
            del pdf.docinfo[key]

    out = io.BytesIO()
    pdf.save(out, min_version="1.7", deterministic_id=True, linearize=False,
             object_stream_mode=pikepdf.ObjectStreamMode.disable)
    data = out.getvalue()
    return Envelope(pdf_bytes=data, attachment_name=name, ips_sha256=hashlib.sha256(ips_json).hexdigest(),
                    pdf_sha256=hashlib.sha256(data).hexdigest())
